"""auto_table

Revision ID: 2f732ed55091
Revises: 88000ba4c2be
Create Date: 2022-09-27 15:38:00.894678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f732ed55091'
down_revision = '88000ba4c2be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('contactnumber', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('selectcourse', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_contactnumber'), 'Users', ['contactnumber'], unique=False)
    op.create_index(op.f('ix_Users_dob'), 'Users', ['dob'], unique=False)
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=False)
    op.create_index(op.f('ix_Users_fullname'), 'Users', ['fullname'], unique=False)
    op.create_index(op.f('ix_Users_gender'), 'Users', ['gender'], unique=False)
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    op.create_index(op.f('ix_Users_reason'), 'Users', ['reason'], unique=False)
    op.create_index(op.f('ix_Users_selectcourse'), 'Users', ['selectcourse'], unique=False)
    op.create_table('Post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['Post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
   # op.drop_table('sample')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('sample',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.Column('Age', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='sample_pkey')
    # )
    op.drop_table('vote')
    op.drop_table('Post')
    op.drop_index(op.f('ix_Users_selectcourse'), table_name='Users')
    op.drop_index(op.f('ix_Users_reason'), table_name='Users')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_index(op.f('ix_Users_gender'), table_name='Users')
    op.drop_index(op.f('ix_Users_fullname'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_index(op.f('ix_Users_dob'), table_name='Users')
    op.drop_index(op.f('ix_Users_contactnumber'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
