name: Build and deploy
on: [push , pull_request]
jobs:
  build:
    environment:
      name: secrets
    env: 
      DB_URL: ${{secrets.DB_URL}}
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: pulling from git
        uses: actions/checkout@v2
      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: install packages
        run: pip install -r requirements.txt
      - name: testing
        run: pytest -s -v

