name: Build and deploy
on: [push , pull_request]
jobs:
  build:
    environment:
      name: secrets
    env: 
      DB_URL: ${{secrets.DB_URL}}

    runs-on: ubuntu-latest
    steps:
      - name: pulling from git
        uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: install packages
        run: pip install -r requirements.txt

      - name: setup postgresql DB
        uses: ikalnytskyi/action-setup-postgres@v3
        with:
          username: postgres
          password: postgres
          database: postgres_test
          port: 5432
        id: postgres

      - name: testing
        run: pytest -s -v

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: deployment
    steps:
      - name: pull from git repo.
        uses: actions/checkout@v2
      - name: Deploy on heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.KEY}}
          heroku_app_name: ${{secrets.APP}} #Must be unique in Heroku
          heroku_email: ${{secrets.EMAIL}}  
